name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Change directory and get dependencies
        run: |
          cd flutter_app
          flutter pub get

      - name: Change directory and run tests
        run: |
          cd flutter_app
          flutter test

      - name: Change directory and build APK
        run: |
          cd flutter_app
          flutter build apk
